# Generated by Django 4.2.7 on 2026-01-21 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madde_no', models.CharField(db_index=True, max_length=50, verbose_name='Madde No')),
                ('baslik', models.CharField(max_length=255, verbose_name='Başlık')),
                ('sayfa', models.IntegerField(default=1, verbose_name='Sayfa')),
                ('order', models.IntegerField(default=0, help_text='Gösterim sırası', verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Konu',
                'verbose_name_plural': 'Konular',
                'ordering': ['order', 'madde_no'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numara', models.CharField(db_index=True, max_length=50, verbose_name='Numara')),
                ('durum', models.TextField(blank=True, verbose_name='Durum')),
                ('soru', models.TextField(verbose_name='Soru')),
                ('siklar', models.JSONField(help_text='Şıklar listesi', verbose_name='Şıklar')),
                ('dogru_cevap', models.TextField(verbose_name='Doğru Cevap')),
                ('yorum', models.TextField(blank=True, verbose_name='Yorum')),
                ('sayfa', models.IntegerField(default=1, verbose_name='Sayfa')),
                ('order', models.IntegerField(default=0, help_text='Konu içindeki sıra', verbose_name='Sıra')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ornekler', to='accounts.topic', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'ordering': ['topic', 'order', 'numara'],
                'unique_together': {('topic', 'numara')},
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numara', models.CharField(max_length=50, verbose_name='Numara')),
                ('metin', models.TextField(verbose_name='Metin')),
                ('sayfa', models.IntegerField(default=1, verbose_name='Sayfa')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aciklamalar', to='accounts.topic', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Açıklama',
                'verbose_name_plural': 'Açıklamalar',
                'ordering': ['topic', 'numara'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.TextField(verbose_name='Seçilen Cevap')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Doğru mu?')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Cevaplanma Tarihi')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='accounts.question', verbose_name='Soru')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Cevabı',
                'verbose_name_plural': 'Kullanıcı Cevapları',
                'ordering': ['-answered_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
